filebeat.modules:
  - module: mysql
    error:
      var.paths: ["/var/log/mysql/error.log*"]
    slowlog:
      var.paths: ["/var/log/mysql/mysql-slow.log*"]
#output.elasticsearch:
#  hosts: ["elasticsearch:9200"]
output.logstash:
  hosts: ["graylog:5044"]
